from __future__ import annotations

import argparse
import json
import logging
import os
import re
import random
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset
from tqdm.auto import tqdm
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    get_linear_schedule_with_warmup,
)
from peft import (
    LoraConfig,
    TaskType,
    get_peft_model,
    prepare_model_for_kbit_training,
    PeftModel,
)


TIMEOUT = 14100   
LOGGER = logging.getLogger(__name__)

LANG_NAMES = {
    "en": "English", "english": "English",
    "hi": "Hindi",   "hindi": "Hindi",
    "bn": "Bengali",  "bengali": "Bengali",
    "kn": "Kannada",  "kannada": "Kannada",
    "ta": "Tamil",    "tamil": "Tamil",
}

MODEL_CONFIGS = {
    "qwen": {
        "lr":               2e-4,
        "lora_target_mods": "q_proj,v_proj,k_proj,o_proj",
        "torch_dtype":      torch.float16,   
        "grad_clip":        1.0,
    },
    "llama": {
        "lr":               5e-5,           
        "lora_target_mods": "q_proj,v_proj,k_proj,o_proj,gate_proj,up_proj,down_proj",
        "torch_dtype":      torch.bfloat16,  
        "grad_clip":        0.3,             
    },
}


def detect_model_family(model_path: str) -> str:
    name = model_path.lower()
    if "llama" in name:
        return "llama"
    if "qwen" in name:
        return "qwen"
    try:
        config_path = Path(model_path) / "config.json"
        if config_path.exists():
            config = json.loads(config_path.read_text())
            arch       = " ".join(config.get("architectures", [])).lower()
            model_type = config.get("model_type", "").lower()
            if "llama" in arch or "llama" in model_type:
                return "llama"
            if "qwen" in arch or "qwen" in model_type:
                return "qwen"
    except Exception:
        pass
    LOGGER.warning(
        "Could not detect model family from '%s' — defaulting to 'qwen'", model_path
    )
    return "qwen"


def format_teacher_prompt(instruction: str, language: str) -> str:
    lang_name = LANG_NAMES.get(language.lower(), "English")
    return (
        f"You are an expert. Answer the following question in {lang_name}.\n"
        f"Think step by step before answering.\n\n"
        f"Write your reasoning inside <reasoning>...</reasoning> tags.\n"
        f"At the end, write your final answer as: #### ANSWER: (X) where X is the correct letter.\n\n"
        f"{instruction}"
    )



def setup_logger(level: str) -> None:
    numeric_level = getattr(logging, level.upper(), logging.INFO)
    logging.basicConfig(
        level=numeric_level,
        format="%(asctime)s | %(levelname)s | %(message)s",
        force=True,
    )


BATCH_SIZE        = 4
GRAD_ACCUM_STEPS  = 4          
EPOCHS            = 5
LR                = 2e-4
WARMUP_RATIO      = 0.05
WEIGHT_DECAY      = 0.01
MAX_LENGTH        = 2048
MASK_PROMPT       = True       
PEFT_METHOD       = "lora"    
LORA_R            = 16
LORA_ALPHA        = 32
LORA_DROPOUT      = 0.05
LORA_TARGET_MODS  = "q_proj,v_proj,k_proj,o_proj"
SEED              = 42

VAL_DATA           = "data/val.jsonl"  
VAL_SAMPLES_PER_LANG = 25             
PATIENCE           = 2
VAL_MAX_NEW_TOKENS = 2048            
ANSWER_RE         = re.compile(r"####\s*ANSWER\s*:\s*\(?([A-J])\)?", re.IGNORECASE)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Distillation training loop")

    parser.add_argument("--student_model", required=True,
                        help="HuggingFace model ID or path to the student model")
    parser.add_argument("--teacher_model", required=False,
                        help="HuggingFace model ID or path to the teacher model")
    parser.add_argument("--train_data", default="data/train.jsonl",
                        help="Path to training data (train.jsonl) generated by the teacher")
    parser.add_argument("--output_dir", required=True,
                        help="Path to save the distilled student model")
    parser.add_argument(
        "--log_level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
    )
    return parser.parse_args()



class DistillDataset(Dataset):


    def __init__(
        self,
        jsonl_path: str,
        tokenizer,
        max_length: int,
        mask_prompt: bool,
        seed: int = 42,
        filter_wrong_answers: bool = True,
    ) -> None:
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.mask_prompt = mask_prompt

        self.records: list[dict] = []
        skipped = 0
        with open(jsonl_path, "r", encoding="utf-8") as fp:
            for line in fp:
                line = line.strip()
                if not line:
                    continue
                record = json.loads(line)
           
                if filter_wrong_answers:
                    gold = str(record.get("gold_answer", "")).strip().upper()[:1]
                    pred = str(record.get("final_answer", "")).strip().upper()[:1]
                    if gold and pred and gold != pred:
                        skipped += 1
                        continue
                self.records.append(record)

        LOGGER.info(
            "Loaded %d records from %s  (skipped %d incorrect teacher answers)",
            len(self.records), jsonl_path, skipped,
        )

        lang_counts = Counter(r.get("language", "unknown") for r in self.records)
        LOGGER.info("Language distribution before shuffle:")
        for lang, count in sorted(lang_counts.items()):
            LOGGER.info("  %-12s : %d samples (%.1f%%)",
                        lang, count, 100 * count / len(self.records))

        rng = random.Random(seed)

        buckets: dict[str, list[dict]] = {}
        for record in self.records:
            lang = record.get("language", "unknown")
            buckets.setdefault(lang, []).append(record)

        for lang in buckets:
            rng.shuffle(buckets[lang])

        interleaved: list[dict] = []
        iterators = [iter(bucket) for bucket in buckets.values()]
        while iterators:
            next_iterators = []
            for it in iterators:
                try:
                    interleaved.append(next(it))
                    next_iterators.append(it)
                except StopIteration:
                    pass  
            iterators = next_iterators

        self.records = interleaved
        LOGGER.info(
            "Dataset shuffled with interleaved strategy (seed=%d). "
            "Total records: %d",
            seed, len(self.records),
        )

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> dict[str, torch.Tensor]:
        record = self.records[idx]

        question: str  = record["question"]
        language: str  = record.get("language", "en")
        generation: str = record.get("teacher_generation", "")

        prompt = format_teacher_prompt(question, language)


        prompt_ids = self.tokenizer(
            prompt,
            add_special_tokens=False,
            truncation=False,
        )["input_ids"]

        full_text = prompt + generation
        encoded = self.tokenizer(
            full_text,
            truncation=True,
            max_length=self.max_length,
            padding=False,
            return_tensors="pt",
        )
        input_ids = encoded["input_ids"][0]         
        attention_mask = encoded["attention_mask"][0]  
        labels = input_ids.clone()                    

        if self.mask_prompt:
            prompt_len = min(len(prompt_ids) + 1, len(labels))
            labels[:prompt_len] = -100

        return {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "labels": labels,
        }



def collate_fn(batch: list[dict], pad_token_id: int) -> dict[str, torch.Tensor]:
    max_len = max(item["input_ids"].size(0) for item in batch)

    input_ids_list, attention_mask_list, labels_list = [], [], []

    for item in batch:
        seq_len = item["input_ids"].size(0)
        pad_len = max_len - seq_len

        input_ids_list.append(
            F.pad(item["input_ids"], (0, pad_len), value=pad_token_id)
        )
        attention_mask_list.append(
            F.pad(item["attention_mask"], (0, pad_len), value=0)
        )
        labels_list.append(
            F.pad(item["labels"], (0, pad_len), value=-100)
        )

    return {
        "input_ids": torch.stack(input_ids_list),
        "attention_mask": torch.stack(attention_mask_list),
        "labels": torch.stack(labels_list),
    }




def load_model_and_tokenizer(student_model: str, model_cfg: dict):

    LOGGER.info("Loading tokenizer from %s", student_model)
    tokenizer = AutoTokenizer.from_pretrained(
        student_model,
        trust_remote_code=True,
        padding_side="right",
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        LOGGER.info("pad_token set to eos_token (%s)", tokenizer.eos_token)

    dtype = model_cfg["torch_dtype"]

    if PEFT_METHOD == "qlora":
        LOGGER.info("Using QLoRA: loading base model in 4-bit NF4 (compute dtype=%s)", dtype)
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=dtype,
            bnb_4bit_use_double_quant=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            student_model,
            quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
        )
        model = prepare_model_for_kbit_training(
            model, use_gradient_checkpointing=True
        )

    elif PEFT_METHOD == "lora":
        LOGGER.info("Using LoRA: loading base model in %s", dtype)
        model = AutoModelForCausalLM.from_pretrained(
            student_model,
            torch_dtype=dtype,
            device_map="auto",
            trust_remote_code=True,
        )
        model.gradient_checkpointing_enable()
        model.config.use_cache = False

    else:
        LOGGER.info("No PEFT: full fine-tuning in %s", dtype)
        model = AutoModelForCausalLM.from_pretrained(
            student_model,
            torch_dtype=dtype,
            device_map="auto",
            trust_remote_code=True,
        )

    if PEFT_METHOD in ("lora", "qlora"):
        target_modules = [m.strip() for m in model_cfg["lora_target_mods"].split(",")]
        LOGGER.info("LoRA target modules: %s", target_modules)
        lora_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=LORA_R,
            lora_alpha=LORA_ALPHA,
            lora_dropout=LORA_DROPOUT,
            target_modules=target_modules,
            bias="none",
        )
        model = get_peft_model(model, lora_config)
        model.print_trainable_parameters()

    return model, tokenizer


def run_epoch(
    model,
    loader: DataLoader,
    optimizer,
    scheduler,
    device: torch.device,
    grad_accum_steps: int,
    training: bool,
    epoch_idx: int,
    grad_clip: float = 1.0,
) -> float:
    """Run one training or validation epoch and return average loss."""
    model.train(training)
    total_loss = 0.0
    total_steps = 0

    if optimizer is not None:
        optimizer.zero_grad()

    pbar = tqdm(
        loader,
        desc=f"{'Train' if training else 'Val'} epoch {epoch_idx + 1}",
        leave=False,
    )

    for step, batch in enumerate(pbar):
    
        input_device = next(model.parameters()).device
        input_ids     = batch["input_ids"].to(input_device)
        attention_mask = batch["attention_mask"].to(input_device)
        labels         = batch["labels"].to(input_device)

        with torch.set_grad_enabled(training):
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )
            loss = outputs.loss / grad_accum_steps

        if training:
            loss.backward()

            if (step + 1) % grad_accum_steps == 0 or (step + 1) == len(loader):
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=grad_clip)
                optimizer.step()
                scheduler.step()
                optimizer.zero_grad()

        total_loss += loss.item() * grad_accum_steps  
        total_steps += 1
        pbar.set_postfix(loss=f"{total_loss / total_steps:.4f}")

    return total_loss / max(total_steps, 1)



def eval_accuracy_on_val(model, tokenizer, val_jsonl: str, device: torch.device) -> float:

    lang_buckets: dict[str, list] = {}
    with open(val_jsonl, "r", encoding="utf-8") as fp:
        for line in fp:
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            lang = record.get("language", "unknown")
            lang_buckets.setdefault(lang, []).append(record)

    rng = random.Random(SEED)
    sampled: list[dict] = []
    for lang, bucket in sorted(lang_buckets.items()):
        chosen = bucket[:VAL_SAMPLES_PER_LANG] if len(bucket) <= VAL_SAMPLES_PER_LANG \
                 else rng.sample(bucket, VAL_SAMPLES_PER_LANG)
        sampled.extend(chosen)

    LOGGER.info("Val subset: %d samples (%d per language)", len(sampled), VAL_SAMPLES_PER_LANG)

    prompts = [format_teacher_prompt(r["question"], r.get("language", "en")) for r in sampled]
    golds   = [str(r.get("gold_answer", "")).strip().upper()[:1] for r in sampled]
    langs   = [r.get("language", "unknown") for r in sampled]

    predictions: list[str] = []
    VAL_BATCH_SIZE = 8

    model.eval()
    tokenizer.padding_side = "left"

    with torch.no_grad():
        for i in tqdm(range(0, len(prompts), VAL_BATCH_SIZE),
                      desc="Val accuracy", leave=False):
            batch_prompts = prompts[i: i + VAL_BATCH_SIZE]

            inputs = tokenizer(
                batch_prompts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=MAX_LENGTH,
            ).to(next(model.parameters()).device)

            output_ids = model.generate(
                **inputs,
                max_new_tokens=VAL_MAX_NEW_TOKENS,
                do_sample=False,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )

            input_len = inputs["input_ids"].shape[1]
            for out_ids in output_ids:
                generated = tokenizer.decode(out_ids[input_len:], skip_special_tokens=True)
                match = ANSWER_RE.search(generated)
                predictions.append(match.group(1).upper() if match else "")

    tokenizer.padding_side = "right"

    lang_correct: dict[str, int] = {}
    lang_total:   dict[str, int] = {}
    total_correct = 0

    for pred, gold, lang in zip(predictions, golds, langs):
        lang_total[lang]   = lang_total.get(lang, 0) + 1
        lang_correct[lang] = lang_correct.get(lang, 0) + (1 if pred == gold else 0)
        if pred == gold:
            total_correct += 1

    LOGGER.info("── Val accuracy breakdown ──────────────────────")
    for lang in sorted(lang_total.keys()):
        c, t = lang_correct[lang], lang_total[lang]
        LOGGER.info("  %-12s : %d/%d = %.2f%%", lang, c, t, 100 * c / t)
    overall = total_correct / len(sampled) if sampled else 0.0
    LOGGER.info("  %-12s : %d/%d = %.2f%%", "OVERALL", total_correct, len(sampled), overall * 100)
    LOGGER.info("────────────────────────────────────────────────")

    return overall


def main() -> None:
    args = parse_args()
    setup_logger(args.log_level)

    output_path = Path(args.output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    LOGGER.info("Using device: %s", device)

    family   = detect_model_family(args.student_model)
    model_cfg = MODEL_CONFIGS[family]
    LOGGER.info("── Model family detected: %s ─────────────────────────", family.upper())
    LOGGER.info("  lr               = %.2e", model_cfg["lr"])
    LOGGER.info("  torch_dtype      = %s",   model_cfg["torch_dtype"])
    LOGGER.info("  grad_clip        = %.1f", model_cfg["grad_clip"])
    LOGGER.info("  lora_target_mods = %s",   model_cfg["lora_target_mods"])
    LOGGER.info("────────────────────────────────────────────────────────")

    model, tokenizer = load_model_and_tokenizer(args.student_model, model_cfg)

    if not hasattr(model, "hf_device_map"):
        model = model.to(device)

    LOGGER.info("Building training dataset from %s", args.train_data)
    train_dataset = DistillDataset(
        jsonl_path=args.train_data,
        tokenizer=tokenizer,
        max_length=MAX_LENGTH,
        mask_prompt=MASK_PROMPT,
        seed=SEED,
    )

    pad_id = tokenizer.pad_token_id
    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        collate_fn=lambda b: collate_fn(b, pad_id),
        num_workers=2,
        pin_memory=True,
    )

    lr = model_cfg["lr"]   
    trainable_params = [p for p in model.parameters() if p.requires_grad]
    LOGGER.info("Trainable parameter tensors: %d", len(trainable_params))

    optimizer = AdamW(
        trainable_params,
        lr=lr,
        weight_decay=WEIGHT_DECAY,
        betas=(0.9, 0.999),
        eps=1e-8,
    )

    total_steps = (len(train_loader) // GRAD_ACCUM_STEPS) * EPOCHS
    warmup_steps = int(total_steps * WARMUP_RATIO)
    LOGGER.info("Scheduler: %d total steps, %d warmup steps", total_steps, warmup_steps)

    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )

    LOGGER.info(
        "Starting training: epochs=%d, batch=%d, grad_accum=%d, lr=%.2e",
        EPOCHS, BATCH_SIZE, GRAD_ACCUM_STEPS, lr,
    )

    best_val_acc = -1.0
    best_epoch   = -1
    no_improve   = 0
    start_time   = time.time()

    for epoch in range(EPOCHS):
        if time.time() - start_time > TIMEOUT:
            LOGGER.info("Reached timeout of %d seconds. Stopping.", TIMEOUT)
            break
        train_loss = run_epoch(
            model=model,
            loader=train_loader,
            optimizer=optimizer,
            scheduler=scheduler,
            device=device,
            grad_accum_steps=GRAD_ACCUM_STEPS,
            training=True,
            epoch_idx=epoch,
            grad_clip=model_cfg["grad_clip"],
        )
        LOGGER.info("Epoch %d/%d | train_loss=%.4f", epoch + 1, EPOCHS, train_loss)

        ckpt_path = output_path / f"checkpoint_epoch_{epoch + 1}"
        model.save_pretrained(ckpt_path)
        tokenizer.save_pretrained(ckpt_path)
        LOGGER.info("Saved checkpoint to %s", ckpt_path)

        if VAL_DATA:
            val_acc = eval_accuracy_on_val(model, tokenizer, VAL_DATA, device)

            if val_acc > best_val_acc:
                best_val_acc = val_acc
                best_epoch   = epoch + 1
                no_improve   = 0
                best_ckpt_path = output_path / "best_checkpoint"
                model.save_pretrained(best_ckpt_path)
                tokenizer.save_pretrained(best_ckpt_path)
                LOGGER.info("  ↳ New best val_acc=%.2f%% — saved best_checkpoint", best_val_acc * 100)
            else:
                no_improve += 1
                LOGGER.info("  ↳ No improvement (%d/%d). Best: epoch %d (%.2f%%)",
                            no_improve, PATIENCE, best_epoch, best_val_acc * 100)
                if no_improve >= PATIENCE:
                    LOGGER.info(
                        "Early stopping at epoch %d. Best epoch: %d | val_acc: %.2f%%",
                        epoch + 1, best_epoch, best_val_acc * 100,
                    )
                    break

    final_path = output_path / "final_model"
    LOGGER.info("Saving final model to %s", final_path)
    model.save_pretrained(final_path)
    tokenizer.save_pretrained(final_path)

    if VAL_DATA:
        LOGGER.info("Training complete. Best checkpoint: epoch %d | val_acc=%.2f%%",
                    best_epoch, best_val_acc * 100)
    else:
        LOGGER.info("Training complete.")


if __name__ == "__main__":
    main()